export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USRE_INFO_SUCCESS = "USRE_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";
export const USER_INFO_LOGOUT = "USER_INFO_LOGOUT";